package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBusiness<M extends BaseBusiness<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setCreatedDate(java.util.Date createdDate) {
		set("created_date", createdDate);
	}

	public java.util.Date getCreatedDate() {
		return get("created_date");
	}

	public void setLastModifiedDate(java.util.Date lastModifiedDate) {
		set("last_modified_date", lastModifiedDate);
	}

	public java.util.Date getLastModifiedDate() {
		return get("last_modified_date");
	}

	public void setVersion(java.lang.Long version) {
		set("version", version);
	}

	public java.lang.Long getVersion() {
		return getLong("version");
	}

	public void setIsEnabled(java.lang.Boolean isEnabled) {
		set("is_enabled", isEnabled);
	}

	public java.lang.Boolean getIsEnabled() {
		return get("is_enabled");
	}

	public void setIsLocked(java.lang.Boolean isLocked) {
		set("is_locked", isLocked);
	}

	public java.lang.Boolean getIsLocked() {
		return get("is_locked");
	}

	public void setLastLoginDate(java.util.Date lastLoginDate) {
		set("last_login_date", lastLoginDate);
	}

	public java.util.Date getLastLoginDate() {
		return get("last_login_date");
	}

	public void setLastLoginIp(java.lang.String lastLoginIp) {
		set("last_login_ip", lastLoginIp);
	}

	public java.lang.String getLastLoginIp() {
		return getStr("last_login_ip");
	}

	public void setLockDate(java.util.Date lockDate) {
		set("lock_date", lockDate);
	}

	public java.util.Date getLockDate() {
		return get("lock_date");
	}

	public void setAttributeValue0(java.lang.String attributeValue0) {
		set("attribute_value0", attributeValue0);
	}

	public java.lang.String getAttributeValue0() {
		return getStr("attribute_value0");
	}

	public void setAttributeValue1(java.lang.String attributeValue1) {
		set("attribute_value1", attributeValue1);
	}

	public java.lang.String getAttributeValue1() {
		return getStr("attribute_value1");
	}

	public void setAttributeValue10(java.lang.String attributeValue10) {
		set("attribute_value10", attributeValue10);
	}

	public java.lang.String getAttributeValue10() {
		return getStr("attribute_value10");
	}

	public void setAttributeValue11(java.lang.String attributeValue11) {
		set("attribute_value11", attributeValue11);
	}

	public java.lang.String getAttributeValue11() {
		return getStr("attribute_value11");
	}

	public void setAttributeValue12(java.lang.String attributeValue12) {
		set("attribute_value12", attributeValue12);
	}

	public java.lang.String getAttributeValue12() {
		return getStr("attribute_value12");
	}

	public void setAttributeValue13(java.lang.String attributeValue13) {
		set("attribute_value13", attributeValue13);
	}

	public java.lang.String getAttributeValue13() {
		return getStr("attribute_value13");
	}

	public void setAttributeValue14(java.lang.String attributeValue14) {
		set("attribute_value14", attributeValue14);
	}

	public java.lang.String getAttributeValue14() {
		return getStr("attribute_value14");
	}

	public void setAttributeValue15(java.lang.String attributeValue15) {
		set("attribute_value15", attributeValue15);
	}

	public java.lang.String getAttributeValue15() {
		return getStr("attribute_value15");
	}

	public void setAttributeValue16(java.lang.String attributeValue16) {
		set("attribute_value16", attributeValue16);
	}

	public java.lang.String getAttributeValue16() {
		return getStr("attribute_value16");
	}

	public void setAttributeValue17(java.lang.String attributeValue17) {
		set("attribute_value17", attributeValue17);
	}

	public java.lang.String getAttributeValue17() {
		return getStr("attribute_value17");
	}

	public void setAttributeValue18(java.lang.String attributeValue18) {
		set("attribute_value18", attributeValue18);
	}

	public java.lang.String getAttributeValue18() {
		return getStr("attribute_value18");
	}

	public void setAttributeValue19(java.lang.String attributeValue19) {
		set("attribute_value19", attributeValue19);
	}

	public java.lang.String getAttributeValue19() {
		return getStr("attribute_value19");
	}

	public void setAttributeValue2(java.lang.String attributeValue2) {
		set("attribute_value2", attributeValue2);
	}

	public java.lang.String getAttributeValue2() {
		return getStr("attribute_value2");
	}

	public void setAttributeValue3(java.lang.String attributeValue3) {
		set("attribute_value3", attributeValue3);
	}

	public java.lang.String getAttributeValue3() {
		return getStr("attribute_value3");
	}

	public void setAttributeValue4(java.lang.String attributeValue4) {
		set("attribute_value4", attributeValue4);
	}

	public java.lang.String getAttributeValue4() {
		return getStr("attribute_value4");
	}

	public void setAttributeValue5(java.lang.String attributeValue5) {
		set("attribute_value5", attributeValue5);
	}

	public java.lang.String getAttributeValue5() {
		return getStr("attribute_value5");
	}

	public void setAttributeValue6(java.lang.String attributeValue6) {
		set("attribute_value6", attributeValue6);
	}

	public java.lang.String getAttributeValue6() {
		return getStr("attribute_value6");
	}

	public void setAttributeValue7(java.lang.String attributeValue7) {
		set("attribute_value7", attributeValue7);
	}

	public java.lang.String getAttributeValue7() {
		return getStr("attribute_value7");
	}

	public void setAttributeValue8(java.lang.String attributeValue8) {
		set("attribute_value8", attributeValue8);
	}

	public java.lang.String getAttributeValue8() {
		return getStr("attribute_value8");
	}

	public void setAttributeValue9(java.lang.String attributeValue9) {
		set("attribute_value9", attributeValue9);
	}

	public java.lang.String getAttributeValue9() {
		return getStr("attribute_value9");
	}

	public void setBalance(java.math.BigDecimal balance) {
		set("balance", balance);
	}

	public java.math.BigDecimal getBalance() {
		return get("balance");
	}

	public void setBankAccount(java.lang.String bankAccount) {
		set("bank_account", bankAccount);
	}

	public java.lang.String getBankAccount() {
		return getStr("bank_account");
	}

	public void setBankName(java.lang.String bankName) {
		set("bank_name", bankName);
	}

	public java.lang.String getBankName() {
		return getStr("bank_name");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return getStr("email");
	}

	public void setFrozenFund(java.math.BigDecimal frozenFund) {
		set("frozen_fund", frozenFund);
	}

	public java.math.BigDecimal getFrozenFund() {
		return get("frozen_fund");
	}

	public void setIdCard(java.lang.String idCard) {
		set("id_card", idCard);
	}

	public java.lang.String getIdCard() {
		return getStr("id_card");
	}

	public void setIdCardImage(java.lang.String idCardImage) {
		set("id_card_image", idCardImage);
	}

	public java.lang.String getIdCardImage() {
		return getStr("id_card_image");
	}

	public void setIdentificationNumber(java.lang.String identificationNumber) {
		set("identification_number", identificationNumber);
	}

	public java.lang.String getIdentificationNumber() {
		return getStr("identification_number");
	}

	public void setLegalPerson(java.lang.String legalPerson) {
		set("legal_person", legalPerson);
	}

	public java.lang.String getLegalPerson() {
		return getStr("legal_person");
	}

	public void setLicenseImage(java.lang.String licenseImage) {
		set("license_image", licenseImage);
	}

	public java.lang.String getLicenseImage() {
		return getStr("license_image");
	}

	public void setLicenseNumber(java.lang.String licenseNumber) {
		set("license_number", licenseNumber);
	}

	public java.lang.String getLicenseNumber() {
		return getStr("license_number");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public void setOrganizationCode(java.lang.String organizationCode) {
		set("organization_code", organizationCode);
	}

	public java.lang.String getOrganizationCode() {
		return getStr("organization_code");
	}

	public void setOrganizationImage(java.lang.String organizationImage) {
		set("organization_image", organizationImage);
	}

	public java.lang.String getOrganizationImage() {
		return getStr("organization_image");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public void setSafekeyExpire(java.util.Date safekeyExpire) {
		set("safeKey_expire", safekeyExpire);
	}

	public java.util.Date getSafekeyExpire() {
		return get("safeKey_expire");
	}

	public void setSafekeyValue(java.lang.String safekeyValue) {
		set("safeKey_value", safekeyValue);
	}

	public java.lang.String getSafekeyValue() {
		return getStr("safeKey_value");
	}

	public void setTaxImage(java.lang.String taxImage) {
		set("tax_image", taxImage);
	}

	public java.lang.String getTaxImage() {
		return getStr("tax_image");
	}

	public void setHasher(java.lang.String hasher) {
		set("hasher", hasher);
	}

	public java.lang.String getHasher() {
		return getStr("hasher");
	}

	public void setSalt(java.lang.String salt) {
		set("salt", salt);
	}

	public java.lang.String getSalt() {
		return getStr("salt");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return getStr("password");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return getStr("username");
	}

}
