package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMemberRole<M extends BaseMemberRole<M>> extends Model<M> implements IBean {

	public void setMembersId(java.lang.Long membersId) {
		set("members_id", membersId);
	}

	public java.lang.Long getMembersId() {
		return getLong("members_id");
	}

	public void setRolesId(java.lang.Long rolesId) {
		set("roles_id", rolesId);
	}

	public java.lang.Long getRolesId() {
		return getLong("roles_id");
	}

}
