package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePromotionMemberRank<M extends BasePromotionMemberRank<M>> extends Model<M> implements IBean {

	public void setPromotionsId(java.lang.Long promotionsId) {
		set("promotions_id", promotionsId);
	}

	public java.lang.Long getPromotionsId() {
		return getLong("promotions_id");
	}

	public void setMemberRanksId(java.lang.Long memberRanksId) {
		set("member_ranks_id", memberRanksId);
	}

	public java.lang.Long getMemberRanksId() {
		return getLong("member_ranks_id");
	}

}
