package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePromotionSku<M extends BasePromotionSku<M>> extends Model<M> implements IBean {

	public void setGiftPromotionsId(java.lang.Long giftPromotionsId) {
		set("gift_promotions_id", giftPromotionsId);
	}

	public java.lang.Long getGiftPromotionsId() {
		return getLong("gift_promotions_id");
	}

	public void setGiftsId(java.lang.Long giftsId) {
		set("gifts_id", giftsId);
	}

	public java.lang.Long getGiftsId() {
		return getLong("gifts_id");
	}

}
