package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProductCategoryBrand<M extends BaseProductCategoryBrand<M>> extends Model<M> implements IBean {

	public void setProductCategoriesId(java.lang.Long productCategoriesId) {
		set("product_categories_id", productCategoriesId);
	}

	public java.lang.Long getProductCategoriesId() {
		return getLong("product_categories_id");
	}

	public void setBrandsId(java.lang.Long brandsId) {
		set("brands_id", brandsId);
	}

	public java.lang.Long getBrandsId() {
		return getLong("brands_id");
	}

}
