package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePromotionPluginSvc<M extends BasePromotionPluginSvc<M>> extends Model<M> implements IBean {

	public void setPromotionPluginId(java.lang.String promotionPluginId) {
		set("promotion_plugin_id", promotionPluginId);
	}

	public java.lang.String getPromotionPluginId() {
		return getStr("promotion_plugin_id");
	}

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

}
