package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArticleArticleTag<M extends BaseArticleArticleTag<M>> extends Model<M> implements IBean {

	public void setArticlesId(java.lang.Long articlesId) {
		set("articles_id", articlesId);
	}

	public java.lang.Long getArticlesId() {
		return getLong("articles_id");
	}

	public void setArticleTagsId(java.lang.Long articleTagsId) {
		set("article_tags_id", articleTagsId);
	}

	public java.lang.Long getArticleTagsId() {
		return getLong("article_tags_id");
	}

}
