package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePaymentTransaction<M extends BasePaymentTransaction<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setCreatedDate(java.util.Date createdDate) {
		set("created_date", createdDate);
	}

	public java.util.Date getCreatedDate() {
		return get("created_date");
	}

	public void setLastModifiedDate(java.util.Date lastModifiedDate) {
		set("last_modified_date", lastModifiedDate);
	}

	public java.util.Date getLastModifiedDate() {
		return get("last_modified_date");
	}

	public void setVersion(java.lang.Long version) {
		set("version", version);
	}

	public java.lang.Long getVersion() {
		return getLong("version");
	}

	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}

	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	public void setExpire(java.util.Date expire) {
		set("expire", expire);
	}

	public java.util.Date getExpire() {
		return get("expire");
	}

	public void setFee(java.math.BigDecimal fee) {
		set("fee", fee);
	}

	public java.math.BigDecimal getFee() {
		return get("fee");
	}

	public void setIsSuccess(java.lang.Boolean isSuccess) {
		set("is_success", isSuccess);
	}

	public java.lang.Boolean getIsSuccess() {
		return get("is_success");
	}

	public void setPaymentPluginId(java.lang.String paymentPluginId) {
		set("payment_plugin_id", paymentPluginId);
	}

	public java.lang.String getPaymentPluginId() {
		return getStr("payment_plugin_id");
	}

	public void setPaymentPluginName(java.lang.String paymentPluginName) {
		set("payment_plugin_name", paymentPluginName);
	}

	public java.lang.String getPaymentPluginName() {
		return getStr("payment_plugin_name");
	}

	public void setSn(java.lang.String sn) {
		set("sn", sn);
	}

	public java.lang.String getSn() {
		return getStr("sn");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setOrderId(java.lang.Long orderId) {
		set("order_id", orderId);
	}

	public java.lang.Long getOrderId() {
		return getLong("order_id");
	}

	public void setParentId(java.lang.Long parentId) {
		set("parent_id", parentId);
	}

	public java.lang.Long getParentId() {
		return getLong("parent_id");
	}

	public void setStoreId(java.lang.Long storeId) {
		set("store_id", storeId);
	}

	public java.lang.Long getStoreId() {
		return getLong("store_id");
	}

	public void setSvcId(java.lang.Long svcId) {
		set("svc_id", svcId);
	}

	public java.lang.Long getSvcId() {
		return getLong("svc_id");
	}

	public void setMemberId(java.lang.Long memberId) {
		set("member_id", memberId);
	}

	public java.lang.Long getMemberId() {
		return getLong("member_id");
	}

	public void setBusinessId(java.lang.Long businessId) {
		set("business_id", businessId);
	}

	public java.lang.Long getBusinessId() {
		return getLong("business_id");
	}

}
