package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePromotion<M extends BasePromotion<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setCreatedDate(java.util.Date createdDate) {
		set("created_date", createdDate);
	}

	public java.util.Date getCreatedDate() {
		return get("created_date");
	}

	public void setLastModifiedDate(java.util.Date lastModifiedDate) {
		set("last_modified_date", lastModifiedDate);
	}

	public java.util.Date getLastModifiedDate() {
		return get("last_modified_date");
	}

	public void setVersion(java.lang.Long version) {
		set("version", version);
	}

	public java.lang.Long getVersion() {
		return getLong("version");
	}

	public void setOrders(java.lang.Integer orders) {
		set("orders", orders);
	}

	public java.lang.Integer getOrders() {
		return getInt("orders");
	}

	public void setBeginDate(java.util.Date beginDate) {
		set("begin_date", beginDate);
	}

	public java.util.Date getBeginDate() {
		return get("begin_date");
	}

	public void setConditionsAmount(java.math.BigDecimal conditionsAmount) {
		set("conditions_amount", conditionsAmount);
	}

	public java.math.BigDecimal getConditionsAmount() {
		return get("conditions_amount");
	}

	public void setConditionsNumber(java.lang.Integer conditionsNumber) {
		set("conditions_number", conditionsNumber);
	}

	public java.lang.Integer getConditionsNumber() {
		return getInt("conditions_number");
	}

	public void setCreditAmount(java.math.BigDecimal creditAmount) {
		set("credit_amount", creditAmount);
	}

	public java.math.BigDecimal getCreditAmount() {
		return get("credit_amount");
	}

	public void setCreditNumber(java.lang.Integer creditNumber) {
		set("credit_number", creditNumber);
	}

	public java.lang.Integer getCreditNumber() {
		return getInt("credit_number");
	}

	public void setDiscount(java.lang.Double discount) {
		set("discount", discount);
	}

	public java.lang.Double getDiscount() {
		return getDouble("discount");
	}

	public void setEndDate(java.util.Date endDate) {
		set("end_date", endDate);
	}

	public java.util.Date getEndDate() {
		return get("end_date");
	}

	public void setImage(java.lang.String image) {
		set("image", image);
	}

	public java.lang.String getImage() {
		return getStr("image");
	}

	public void setIntroduction(java.lang.String introduction) {
		set("introduction", introduction);
	}

	public java.lang.String getIntroduction() {
		return getStr("introduction");
	}

	public void setIsCouponAllowed(java.lang.Boolean isCouponAllowed) {
		set("is_coupon_allowed", isCouponAllowed);
	}

	public java.lang.Boolean getIsCouponAllowed() {
		return get("is_coupon_allowed");
	}

	public void setIsEnabled(java.lang.Boolean isEnabled) {
		set("is_enabled", isEnabled);
	}

	public java.lang.Boolean getIsEnabled() {
		return get("is_enabled");
	}

	public void setIsFreeShipping(java.lang.Boolean isFreeShipping) {
		set("is_free_shipping", isFreeShipping);
	}

	public java.lang.Boolean getIsFreeShipping() {
		return get("is_free_shipping");
	}

	public void setMaximumPrice(java.math.BigDecimal maximumPrice) {
		set("maximum_price", maximumPrice);
	}

	public java.math.BigDecimal getMaximumPrice() {
		return get("maximum_price");
	}

	public void setMaximumQuantity(java.lang.Integer maximumQuantity) {
		set("maximum_quantity", maximumQuantity);
	}

	public java.lang.Integer getMaximumQuantity() {
		return getInt("maximum_quantity");
	}

	public void setMinimumPrice(java.math.BigDecimal minimumPrice) {
		set("minimum_price", minimumPrice);
	}

	public java.math.BigDecimal getMinimumPrice() {
		return get("minimum_price");
	}

	public void setMinimumQuantity(java.lang.Integer minimumQuantity) {
		set("minimum_quantity", minimumQuantity);
	}

	public java.lang.Integer getMinimumQuantity() {
		return getInt("minimum_quantity");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public void setPriceExpression(java.lang.String priceExpression) {
		set("price_expression", priceExpression);
	}

	public java.lang.String getPriceExpression() {
		return getStr("price_expression");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setStoreId(java.lang.Long storeId) {
		set("store_id", storeId);
	}

	public java.lang.Long getStoreId() {
		return getLong("store_id");
	}

}
