package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIdGenerator<M extends BaseIdGenerator<M>> extends Model<M> implements IBean {

	public void setSequenceName(java.lang.String sequenceName) {
		set("sequence_name", sequenceName);
	}

	public java.lang.String getSequenceName() {
		return getStr("sequence_name");
	}

	public void setNextVal(java.lang.Long nextVal) {
		set("next_val", nextVal);
	}

	public java.lang.Long getNextVal() {
		return getLong("next_val");
	}

}
