package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdminRole<M extends BaseAdminRole<M>> extends Model<M> implements IBean {

	public void setAdminsId(java.lang.Long adminsId) {
		set("admins_id", adminsId);
	}

	public java.lang.Long getAdminsId() {
		return getLong("admins_id");
	}

	public void setRolesId(java.lang.Long rolesId) {
		set("roles_id", rolesId);
	}

	public java.lang.Long getRolesId() {
		return getLong("roles_id");
	}

}
