package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMessageConfig<M extends BaseMessageConfig<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setCreatedDate(java.util.Date createdDate) {
		set("created_date", createdDate);
	}

	public java.util.Date getCreatedDate() {
		return get("created_date");
	}

	public void setLastModifiedDate(java.util.Date lastModifiedDate) {
		set("last_modified_date", lastModifiedDate);
	}

	public java.util.Date getLastModifiedDate() {
		return get("last_modified_date");
	}

	public void setVersion(java.lang.Long version) {
		set("version", version);
	}

	public java.lang.Long getVersion() {
		return getLong("version");
	}

	public void setIsMailEnabled(java.lang.Boolean isMailEnabled) {
		set("is_mail_enabled", isMailEnabled);
	}

	public java.lang.Boolean getIsMailEnabled() {
		return get("is_mail_enabled");
	}

	public void setIsSmsEnabled(java.lang.Boolean isSmsEnabled) {
		set("is_sms_enabled", isSmsEnabled);
	}

	public java.lang.Boolean getIsSmsEnabled() {
		return get("is_sms_enabled");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return getInt("type");
	}

}
