package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArticle<M extends BaseArticle<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setCreatedDate(java.util.Date createdDate) {
		set("created_date", createdDate);
	}

	public java.util.Date getCreatedDate() {
		return get("created_date");
	}

	public void setLastModifiedDate(java.util.Date lastModifiedDate) {
		set("last_modified_date", lastModifiedDate);
	}

	public java.util.Date getLastModifiedDate() {
		return get("last_modified_date");
	}

	public void setVersion(java.lang.Long version) {
		set("version", version);
	}

	public java.lang.Long getVersion() {
		return getLong("version");
	}

	public void setAuthor(java.lang.String author) {
		set("author", author);
	}

	public java.lang.String getAuthor() {
		return getStr("author");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setHits(java.lang.Long hits) {
		set("hits", hits);
	}

	public java.lang.Long getHits() {
		return getLong("hits");
	}

	public void setIsPublication(java.lang.Boolean isPublication) {
		set("is_publication", isPublication);
	}

	public java.lang.Boolean getIsPublication() {
		return get("is_publication");
	}

	public void setIsTop(java.lang.Boolean isTop) {
		set("is_top", isTop);
	}

	public java.lang.Boolean getIsTop() {
		return get("is_top");
	}

	public void setSeoDescription(java.lang.String seoDescription) {
		set("seo_description", seoDescription);
	}

	public java.lang.String getSeoDescription() {
		return getStr("seo_description");
	}

	public void setSeoKeywords(java.lang.String seoKeywords) {
		set("seo_keywords", seoKeywords);
	}

	public java.lang.String getSeoKeywords() {
		return getStr("seo_keywords");
	}

	public void setSeoTitle(java.lang.String seoTitle) {
		set("seo_title", seoTitle);
	}

	public java.lang.String getSeoTitle() {
		return getStr("seo_title");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setArticleCategoryId(java.lang.Long articleCategoryId) {
		set("article_category_id", articleCategoryId);
	}

	public java.lang.Long getArticleCategoryId() {
		return getLong("article_category_id");
	}

}
