package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCoupon<M extends BaseCoupon<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setCreatedDate(java.util.Date createdDate) {
		set("created_date", createdDate);
	}

	public java.util.Date getCreatedDate() {
		return get("created_date");
	}

	public void setLastModifiedDate(java.util.Date lastModifiedDate) {
		set("last_modified_date", lastModifiedDate);
	}

	public java.util.Date getLastModifiedDate() {
		return get("last_modified_date");
	}

	public void setVersion(java.lang.Long version) {
		set("version", version);
	}

	public java.lang.Long getVersion() {
		return getLong("version");
	}

	public void setBeginDate(java.util.Date beginDate) {
		set("begin_date", beginDate);
	}

	public java.util.Date getBeginDate() {
		return get("begin_date");
	}

	public void setEndDate(java.util.Date endDate) {
		set("end_date", endDate);
	}

	public java.util.Date getEndDate() {
		return get("end_date");
	}

	public void setIntroduction(java.lang.String introduction) {
		set("introduction", introduction);
	}

	public java.lang.String getIntroduction() {
		return getStr("introduction");
	}

	public void setIsEnabled(java.lang.Boolean isEnabled) {
		set("is_enabled", isEnabled);
	}

	public java.lang.Boolean getIsEnabled() {
		return get("is_enabled");
	}

	public void setIsExchange(java.lang.Boolean isExchange) {
		set("is_exchange", isExchange);
	}

	public java.lang.Boolean getIsExchange() {
		return get("is_exchange");
	}

	public void setMaximumPrice(java.math.BigDecimal maximumPrice) {
		set("maximum_price", maximumPrice);
	}

	public java.math.BigDecimal getMaximumPrice() {
		return get("maximum_price");
	}

	public void setMaximumQuantity(java.lang.Integer maximumQuantity) {
		set("maximum_quantity", maximumQuantity);
	}

	public java.lang.Integer getMaximumQuantity() {
		return getInt("maximum_quantity");
	}

	public void setMinimumPrice(java.math.BigDecimal minimumPrice) {
		set("minimum_price", minimumPrice);
	}

	public java.math.BigDecimal getMinimumPrice() {
		return get("minimum_price");
	}

	public void setMinimumQuantity(java.lang.Integer minimumQuantity) {
		set("minimum_quantity", minimumQuantity);
	}

	public java.lang.Integer getMinimumQuantity() {
		return getInt("minimum_quantity");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public void setPoint(java.lang.Long point) {
		set("point", point);
	}

	public java.lang.Long getPoint() {
		return getLong("point");
	}

	public void setPrefix(java.lang.String prefix) {
		set("prefix", prefix);
	}

	public java.lang.String getPrefix() {
		return getStr("prefix");
	}

	public void setPriceExpression(java.lang.String priceExpression) {
		set("price_expression", priceExpression);
	}

	public java.lang.String getPriceExpression() {
		return getStr("price_expression");
	}

	public void setStoreId(java.lang.Long storeId) {
		set("store_id", storeId);
	}

	public java.lang.Long getStoreId() {
		return getLong("store_id");
	}

}
