package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStore<M extends BaseStore<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setCreatedDate(java.util.Date createdDate) {
		set("created_date", createdDate);
	}

	public java.util.Date getCreatedDate() {
		return get("created_date");
	}

	public void setLastModifiedDate(java.util.Date lastModifiedDate) {
		set("last_modified_date", lastModifiedDate);
	}

	public java.util.Date getLastModifiedDate() {
		return get("last_modified_date");
	}

	public void setVersion(java.lang.Long version) {
		set("version", version);
	}

	public java.lang.Long getVersion() {
		return getLong("version");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setBailPaid(java.math.BigDecimal bailPaid) {
		set("bail_paid", bailPaid);
	}

	public java.math.BigDecimal getBailPaid() {
		return get("bail_paid");
	}

	public void setDiscountPromotionEndDate(java.util.Date discountPromotionEndDate) {
		set("discount_promotion_end_date", discountPromotionEndDate);
	}

	public java.util.Date getDiscountPromotionEndDate() {
		return get("discount_promotion_end_date");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return getStr("email");
	}

	public void setEndDate(java.util.Date endDate) {
		set("end_date", endDate);
	}

	public java.util.Date getEndDate() {
		return get("end_date");
	}

	public void setFullReductionPromotionEndDate(java.util.Date fullReductionPromotionEndDate) {
		set("full_reduction_promotion_end_date", fullReductionPromotionEndDate);
	}

	public java.util.Date getFullReductionPromotionEndDate() {
		return get("full_reduction_promotion_end_date");
	}

	public void setIntroduction(java.lang.String introduction) {
		set("introduction", introduction);
	}

	public java.lang.String getIntroduction() {
		return getStr("introduction");
	}

	public void setIsEnabled(java.lang.Boolean isEnabled) {
		set("is_enabled", isEnabled);
	}

	public java.lang.Boolean getIsEnabled() {
		return get("is_enabled");
	}

	public void setKeyword(java.lang.String keyword) {
		set("keyword", keyword);
	}

	public java.lang.String getKeyword() {
		return getStr("keyword");
	}

	public void setLogo(java.lang.String logo) {
		set("logo", logo);
	}

	public java.lang.String getLogo() {
		return getStr("logo");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setZipCode(java.lang.String zipCode) {
		set("zip_code", zipCode);
	}

	public java.lang.String getZipCode() {
		return getStr("zip_code");
	}

	public void setBusinessId(java.lang.Long businessId) {
		set("business_id", businessId);
	}

	public java.lang.Long getBusinessId() {
		return getLong("business_id");
	}

	public void setStoreCategoryId(java.lang.Long storeCategoryId) {
		set("store_category_id", storeCategoryId);
	}

	public java.lang.Long getStoreCategoryId() {
		return getLong("store_category_id");
	}

	public void setStoreRankId(java.lang.Long storeRankId) {
		set("store_rank_id", storeRankId);
	}

	public java.lang.Long getStoreRankId() {
		return getLong("store_rank_id");
	}

}
