package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProductCategoryStore<M extends BaseProductCategoryStore<M>> extends Model<M> implements IBean {

	public void setStoresId(java.lang.Long storesId) {
		set("stores_id", storesId);
	}

	public java.lang.Long getStoresId() {
		return getLong("stores_id");
	}

	public void setProductCategoriesId(java.lang.Long productCategoriesId) {
		set("product_categories_id", productCategoriesId);
	}

	public java.lang.Long getProductCategoriesId() {
		return getLong("product_categories_id");
	}

}
