package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderItem<M extends BaseOrderItem<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setCreatedDate(java.util.Date createdDate) {
		set("created_date", createdDate);
	}

	public java.util.Date getCreatedDate() {
		return get("created_date");
	}

	public void setLastModifiedDate(java.util.Date lastModifiedDate) {
		set("last_modified_date", lastModifiedDate);
	}

	public java.util.Date getLastModifiedDate() {
		return get("last_modified_date");
	}

	public void setVersion(java.lang.Long version) {
		set("version", version);
	}

	public java.lang.Long getVersion() {
		return getLong("version");
	}

	public void setCommissionTotals(java.math.BigDecimal commissionTotals) {
		set("commission_totals", commissionTotals);
	}

	public java.math.BigDecimal getCommissionTotals() {
		return get("commission_totals");
	}

	public void setIsDelivery(java.lang.Boolean isDelivery) {
		set("is_delivery", isDelivery);
	}

	public java.lang.Boolean getIsDelivery() {
		return get("is_delivery");
	}

	public void setIsReview(java.lang.Boolean isReview) {
		set("is_review", isReview);
	}

	public java.lang.Boolean getIsReview() {
		return get("is_review");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setQuantity(java.lang.Integer quantity) {
		set("quantity", quantity);
	}

	public java.lang.Integer getQuantity() {
		return getInt("quantity");
	}

	public void setReturnedQuantity(java.lang.Integer returnedQuantity) {
		set("returned_quantity", returnedQuantity);
	}

	public java.lang.Integer getReturnedQuantity() {
		return getInt("returned_quantity");
	}

	public void setShippedQuantity(java.lang.Integer shippedQuantity) {
		set("shipped_quantity", shippedQuantity);
	}

	public java.lang.Integer getShippedQuantity() {
		return getInt("shipped_quantity");
	}

	public void setSn(java.lang.String sn) {
		set("sn", sn);
	}

	public java.lang.String getSn() {
		return getStr("sn");
	}

	public void setSpecifications(java.lang.String specifications) {
		set("specifications", specifications);
	}

	public java.lang.String getSpecifications() {
		return getStr("specifications");
	}

	public void setThumbnail(java.lang.String thumbnail) {
		set("thumbnail", thumbnail);
	}

	public java.lang.String getThumbnail() {
		return getStr("thumbnail");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setWeight(java.lang.Integer weight) {
		set("weight", weight);
	}

	public java.lang.Integer getWeight() {
		return getInt("weight");
	}

	public void setOrderId(java.lang.Long orderId) {
		set("order_id", orderId);
	}

	public java.lang.Long getOrderId() {
		return getLong("order_id");
	}

	public void setSkuId(java.lang.Long skuId) {
		set("sku_id", skuId);
	}

	public java.lang.Long getSkuId() {
		return getLong("sku_id");
	}

}
