package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrder<M extends BaseOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setCreatedDate(java.util.Date createdDate) {
		set("created_date", createdDate);
	}

	public java.util.Date getCreatedDate() {
		return get("created_date");
	}

	public void setLastModifiedDate(java.util.Date lastModifiedDate) {
		set("last_modified_date", lastModifiedDate);
	}

	public java.util.Date getLastModifiedDate() {
		return get("last_modified_date");
	}

	public void setVersion(java.lang.Long version) {
		set("version", version);
	}

	public java.lang.Long getVersion() {
		return getLong("version");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}

	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	public void setAmountPaid(java.math.BigDecimal amountPaid) {
		set("amount_paid", amountPaid);
	}

	public java.math.BigDecimal getAmountPaid() {
		return get("amount_paid");
	}

	public void setAreaName(java.lang.String areaName) {
		set("area_name", areaName);
	}

	public java.lang.String getAreaName() {
		return getStr("area_name");
	}

	public void setCompleteDate(java.util.Date completeDate) {
		set("complete_date", completeDate);
	}

	public java.util.Date getCompleteDate() {
		return get("complete_date");
	}

	public void setConsignee(java.lang.String consignee) {
		set("consignee", consignee);
	}

	public java.lang.String getConsignee() {
		return getStr("consignee");
	}

	public void setCouponDiscount(java.math.BigDecimal couponDiscount) {
		set("coupon_discount", couponDiscount);
	}

	public java.math.BigDecimal getCouponDiscount() {
		return get("coupon_discount");
	}

	public void setExchangePoint(java.lang.Long exchangePoint) {
		set("exchange_point", exchangePoint);
	}

	public java.lang.Long getExchangePoint() {
		return getLong("exchange_point");
	}

	public void setExpire(java.util.Date expire) {
		set("expire", expire);
	}

	public java.util.Date getExpire() {
		return get("expire");
	}

	public void setFee(java.math.BigDecimal fee) {
		set("fee", fee);
	}

	public java.math.BigDecimal getFee() {
		return get("fee");
	}

	public void setFreight(java.math.BigDecimal freight) {
		set("freight", freight);
	}

	public java.math.BigDecimal getFreight() {
		return get("freight");
	}

	public void setInvoiceContent(java.lang.String invoiceContent) {
		set("invoice_content", invoiceContent);
	}

	public java.lang.String getInvoiceContent() {
		return getStr("invoice_content");
	}

	public void setInvoiceTitle(java.lang.String invoiceTitle) {
		set("invoice_title", invoiceTitle);
	}

	public java.lang.String getInvoiceTitle() {
		return getStr("invoice_title");
	}

	public void setIsAllocatedStock(java.lang.Boolean isAllocatedStock) {
		set("is_allocated_stock", isAllocatedStock);
	}

	public java.lang.Boolean getIsAllocatedStock() {
		return get("is_allocated_stock");
	}

	public void setIsExchangePoint(java.lang.Boolean isExchangePoint) {
		set("is_exchange_point", isExchangePoint);
	}

	public java.lang.Boolean getIsExchangePoint() {
		return get("is_exchange_point");
	}

	public void setIsUseCouponCode(java.lang.Boolean isUseCouponCode) {
		set("is_use_coupon_code", isUseCouponCode);
	}

	public java.lang.Boolean getIsUseCouponCode() {
		return get("is_use_coupon_code");
	}

	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}

	public java.lang.String getMemo() {
		return getStr("memo");
	}

	public void setOffsetAmount(java.math.BigDecimal offsetAmount) {
		set("offset_amount", offsetAmount);
	}

	public java.math.BigDecimal getOffsetAmount() {
		return get("offset_amount");
	}

	public void setPaymentMethodName(java.lang.String paymentMethodName) {
		set("payment_method_name", paymentMethodName);
	}

	public java.lang.String getPaymentMethodName() {
		return getStr("payment_method_name");
	}

	public void setPaymentMethodType(java.lang.Integer paymentMethodType) {
		set("payment_method_type", paymentMethodType);
	}

	public java.lang.Integer getPaymentMethodType() {
		return getInt("payment_method_type");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setPromotionDiscount(java.math.BigDecimal promotionDiscount) {
		set("promotion_discount", promotionDiscount);
	}

	public java.math.BigDecimal getPromotionDiscount() {
		return get("promotion_discount");
	}

	public void setPromotionNames(java.lang.String promotionNames) {
		set("promotion_names", promotionNames);
	}

	public java.lang.String getPromotionNames() {
		return getStr("promotion_names");
	}

	public void setQuantity(java.lang.Integer quantity) {
		set("quantity", quantity);
	}

	public java.lang.Integer getQuantity() {
		return getInt("quantity");
	}

	public void setRefundAmount(java.math.BigDecimal refundAmount) {
		set("refund_amount", refundAmount);
	}

	public java.math.BigDecimal getRefundAmount() {
		return get("refund_amount");
	}

	public void setReturnedQuantity(java.lang.Integer returnedQuantity) {
		set("returned_quantity", returnedQuantity);
	}

	public java.lang.Integer getReturnedQuantity() {
		return getInt("returned_quantity");
	}

	public void setRewardPoint(java.lang.Long rewardPoint) {
		set("reward_point", rewardPoint);
	}

	public java.lang.Long getRewardPoint() {
		return getLong("reward_point");
	}

	public void setShippedQuantity(java.lang.Integer shippedQuantity) {
		set("shipped_quantity", shippedQuantity);
	}

	public java.lang.Integer getShippedQuantity() {
		return getInt("shipped_quantity");
	}

	public void setShippingMethodName(java.lang.String shippingMethodName) {
		set("shipping_method_name", shippingMethodName);
	}

	public java.lang.String getShippingMethodName() {
		return getStr("shipping_method_name");
	}

	public void setSn(java.lang.String sn) {
		set("sn", sn);
	}

	public java.lang.String getSn() {
		return getStr("sn");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setSource(java.lang.Integer source) {
		set("source", source);
	}

	public java.lang.Integer getSource() {
		return getInt("source");
	}

	public void setTax(java.math.BigDecimal tax) {
		set("tax", tax);
	}

	public java.math.BigDecimal getTax() {
		return get("tax");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setWeight(java.lang.Integer weight) {
		set("weight", weight);
	}

	public java.lang.Integer getWeight() {
		return getInt("weight");
	}

	public void setZipCode(java.lang.String zipCode) {
		set("zip_code", zipCode);
	}

	public java.lang.String getZipCode() {
		return getStr("zip_code");
	}

	public void setAreaId(java.lang.Long areaId) {
		set("area_id", areaId);
	}

	public java.lang.Long getAreaId() {
		return getLong("area_id");
	}

	public void setCouponCodeId(java.lang.Long couponCodeId) {
		set("coupon_code_id", couponCodeId);
	}

	public java.lang.Long getCouponCodeId() {
		return getLong("coupon_code_id");
	}

	public void setMemberId(java.lang.Long memberId) {
		set("member_id", memberId);
	}

	public java.lang.Long getMemberId() {
		return getLong("member_id");
	}

	public void setPaymentMethodId(java.lang.Long paymentMethodId) {
		set("payment_method_id", paymentMethodId);
	}

	public java.lang.Long getPaymentMethodId() {
		return getLong("payment_method_id");
	}

	public void setShippingMethodId(java.lang.Long shippingMethodId) {
		set("shipping_method_id", shippingMethodId);
	}

	public java.lang.Long getShippingMethodId() {
		return getLong("shipping_method_id");
	}

	public void setStoreId(java.lang.Long storeId) {
		set("store_id", storeId);
	}

	public java.lang.Long getStoreId() {
		return getLong("store_id");
	}

}
