package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProductProductTag<M extends BaseProductProductTag<M>> extends Model<M> implements IBean {

	public void setProductsId(java.lang.Long productsId) {
		set("products_id", productsId);
	}

	public java.lang.Long getProductsId() {
		return getLong("products_id");
	}

	public void setProductTagsId(java.lang.Long productTagsId) {
		set("product_tags_id", productTagsId);
	}

	public java.lang.Long getProductTagsId() {
		return getLong("product_tags_id");
	}

}
