package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStockLog<M extends BaseStockLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setCreatedDate(java.util.Date createdDate) {
		set("created_date", createdDate);
	}

	public java.util.Date getCreatedDate() {
		return get("created_date");
	}

	public void setLastModifiedDate(java.util.Date lastModifiedDate) {
		set("last_modified_date", lastModifiedDate);
	}

	public java.util.Date getLastModifiedDate() {
		return get("last_modified_date");
	}

	public void setVersion(java.lang.Long version) {
		set("version", version);
	}

	public java.lang.Long getVersion() {
		return getLong("version");
	}

	public void setInQuantity(java.lang.Integer inQuantity) {
		set("in_quantity", inQuantity);
	}

	public java.lang.Integer getInQuantity() {
		return getInt("in_quantity");
	}

	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}

	public java.lang.String getMemo() {
		return getStr("memo");
	}

	public void setOutQuantity(java.lang.Integer outQuantity) {
		set("out_quantity", outQuantity);
	}

	public java.lang.Integer getOutQuantity() {
		return getInt("out_quantity");
	}

	public void setStock(java.lang.Integer stock) {
		set("stock", stock);
	}

	public java.lang.Integer getStock() {
		return getInt("stock");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setSkuId(java.lang.Long skuId) {
		set("sku_id", skuId);
	}

	public java.lang.Long getSkuId() {
		return getLong("sku_id");
	}

}
