package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderShipping<M extends BaseOrderShipping<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setCreatedDate(java.util.Date createdDate) {
		set("created_date", createdDate);
	}

	public java.util.Date getCreatedDate() {
		return get("created_date");
	}

	public void setLastModifiedDate(java.util.Date lastModifiedDate) {
		set("last_modified_date", lastModifiedDate);
	}

	public java.util.Date getLastModifiedDate() {
		return get("last_modified_date");
	}

	public void setVersion(java.lang.Long version) {
		set("version", version);
	}

	public java.lang.Long getVersion() {
		return getLong("version");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setArea(java.lang.String area) {
		set("area", area);
	}

	public java.lang.String getArea() {
		return getStr("area");
	}

	public void setConsignee(java.lang.String consignee) {
		set("consignee", consignee);
	}

	public java.lang.String getConsignee() {
		return getStr("consignee");
	}

	public void setDeliveryCorp(java.lang.String deliveryCorp) {
		set("delivery_corp", deliveryCorp);
	}

	public java.lang.String getDeliveryCorp() {
		return getStr("delivery_corp");
	}

	public void setDeliveryCorpCode(java.lang.String deliveryCorpCode) {
		set("delivery_corp_code", deliveryCorpCode);
	}

	public java.lang.String getDeliveryCorpCode() {
		return getStr("delivery_corp_code");
	}

	public void setDeliveryCorpUrl(java.lang.String deliveryCorpUrl) {
		set("delivery_corp_url", deliveryCorpUrl);
	}

	public java.lang.String getDeliveryCorpUrl() {
		return getStr("delivery_corp_url");
	}

	public void setFreight(java.math.BigDecimal freight) {
		set("freight", freight);
	}

	public java.math.BigDecimal getFreight() {
		return get("freight");
	}

	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}

	public java.lang.String getMemo() {
		return getStr("memo");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public void setShippingMethod(java.lang.String shippingMethod) {
		set("shipping_method", shippingMethod);
	}

	public java.lang.String getShippingMethod() {
		return getStr("shipping_method");
	}

	public void setSn(java.lang.String sn) {
		set("sn", sn);
	}

	public java.lang.String getSn() {
		return getStr("sn");
	}

	public void setTrackingNo(java.lang.String trackingNo) {
		set("tracking_no", trackingNo);
	}

	public java.lang.String getTrackingNo() {
		return getStr("tracking_no");
	}

	public void setZipCode(java.lang.String zipCode) {
		set("zip_code", zipCode);
	}

	public java.lang.String getZipCode() {
		return getStr("zip_code");
	}

	public void setOrderId(java.lang.Long orderId) {
		set("order_id", orderId);
	}

	public java.lang.Long getOrderId() {
		return getLong("order_id");
	}

}
