package com.jfinalshop.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("ad", "id", Ad.class);
		arp.addMapping("ad_position", "id", AdPosition.class);
		arp.addMapping("admin", "id", Admin.class);
		// Composite Primary Key order: admins_id,roles_id
		arp.addMapping("admin_role", "admins_id,roles_id", AdminRole.class);
		arp.addMapping("area", "id", Area.class);
		arp.addMapping("area_freight_config", "id", AreaFreightConfig.class);
		arp.addMapping("article", "id", Article.class);
		// Composite Primary Key order: article_tags_id,articles_id
		arp.addMapping("article_article_tag", "article_tags_id,articles_id", ArticleArticleTag.class);
		arp.addMapping("article_category", "id", ArticleCategory.class);
		arp.addMapping("article_tag", "id", ArticleTag.class);
		arp.addMapping("attribute", "id", Attribute.class);
		arp.addMapping("audit_log", "id", AuditLog.class);
		arp.addMapping("brand", "id", Brand.class);
		arp.addMapping("business", "id", Business.class);
		arp.addMapping("business_attribute", "id", BusinessAttribute.class);
		arp.addMapping("business_deposit_log", "id", BusinessDepositLog.class);
		// Composite Primary Key order: business_id,roles_id
		arp.addMapping("business_role", "business_id,roles_id", BusinessRole.class);
		arp.addMapping("cart", "id", Cart.class);
		arp.addMapping("cart_item", "id", CartItem.class);
		arp.addMapping("cash", "id", Cash.class);
		arp.addMapping("category_application", "id", CategoryApplication.class);
		arp.addMapping("consultation", "id", Consultation.class);
		arp.addMapping("coupon", "id", Coupon.class);
		arp.addMapping("coupon_code", "id", CouponCode.class);
		arp.addMapping("default_freight_config", "id", DefaultFreightConfig.class);
		arp.addMapping("delivery_center", "id", DeliveryCenter.class);
		arp.addMapping("delivery_corp", "id", DeliveryCorp.class);
		arp.addMapping("delivery_template", "id", DeliveryTemplate.class);
		arp.addMapping("friend_link", "id", FriendLink.class);
		arp.addMapping("id_generator", "sequence_name", IdGenerator.class);
		arp.addMapping("instant_message", "id", InstantMessage.class);
		arp.addMapping("member", "id", Member.class);
		arp.addMapping("member_attribute", "id", MemberAttribute.class);
		arp.addMapping("member_deposit_log", "id", MemberDepositLog.class);
		arp.addMapping("member_rank", "id", MemberRank.class);
		// Composite Primary Key order: members_id,roles_id
		arp.addMapping("member_role", "members_id,roles_id", MemberRole.class);
		arp.addMapping("menu", "id", Menu.class);
		arp.addMapping("message", "id", Message.class);
		arp.addMapping("message_config", "id", MessageConfig.class);
		arp.addMapping("navigation", "id", Navigation.class);
		arp.addMapping("order", "id", Order.class);
		arp.addMapping("order_item", "id", OrderItem.class);
		arp.addMapping("order_log", "id", OrderLog.class);
		arp.addMapping("order_payment", "id", OrderPayment.class);
		arp.addMapping("order_refunds", "id", OrderRefunds.class);
		arp.addMapping("order_returns", "id", OrderReturns.class);
		arp.addMapping("order_returns_item", "id", OrderReturnsItem.class);
		arp.addMapping("order_shipping", "id", OrderShipping.class);
		arp.addMapping("order_shipping_item", "id", OrderShippingItem.class);
		arp.addMapping("parameter", "id", Parameter.class);
		arp.addMapping("payment_method", "id", PaymentMethod.class);
		arp.addMapping("payment_transaction", "id", PaymentTransaction.class);
		arp.addMapping("permission", "id", Permission.class);
		// Composite Primary Key order: permissions_id,roles_id
		arp.addMapping("permission_role", "permissions_id,roles_id", PermissionRole.class);
		arp.addMapping("platform_svc", "id", PlatformSvc.class);
		arp.addMapping("plugin_config", "id", PluginConfig.class);
		arp.addMapping("point_log", "id", PointLog.class);
		arp.addMapping("product", "id", Product.class);
		arp.addMapping("product_category", "id", ProductCategory.class);
		// Composite Primary Key order: brands_id,product_categories_id
		arp.addMapping("product_category_brand", "brands_id,product_categories_id", ProductCategoryBrand.class);
		// Composite Primary Key order: product_categories_id,promotions_id
		arp.addMapping("product_category_promotion", "product_categories_id,promotions_id", ProductCategoryPromotion.class);
		// Composite Primary Key order: product_categories_id,stores_id
		arp.addMapping("product_category_store", "product_categories_id,stores_id", ProductCategoryStore.class);
		arp.addMapping("product_favorite", "id", ProductFavorite.class);
		arp.addMapping("product_notify", "id", ProductNotify.class);
		// Composite Primary Key order: product_tags_id,products_id
		arp.addMapping("product_product_tag", "product_tags_id,products_id", ProductProductTag.class);
		// Composite Primary Key order: products_id,promotions_id
		arp.addMapping("product_promotion", "products_id,promotions_id", ProductPromotion.class);
		// Composite Primary Key order: products_id,store_product_tags_id
		arp.addMapping("product_store_product_tag", "products_id,store_product_tags_id", ProductStoreProductTag.class);
		arp.addMapping("product_tag", "id", ProductTag.class);
		arp.addMapping("promotion", "id", Promotion.class);
		// Composite Primary Key order: coupons_id,promotions_id
		arp.addMapping("promotion_coupon", "coupons_id,promotions_id", PromotionCoupon.class);
		// Composite Primary Key order: member_ranks_id,promotions_id
		arp.addMapping("promotion_member_rank", "member_ranks_id,promotions_id", PromotionMemberRank.class);
		arp.addMapping("promotion_plugin_svc", "id", PromotionPluginSvc.class);
		// Composite Primary Key order: gift_promotions_id,gifts_id
		arp.addMapping("promotion_sku", "gift_promotions_id,gifts_id", PromotionSku.class);
		arp.addMapping("receiver", "id", Receiver.class);
		arp.addMapping("review", "id", Review.class);
		arp.addMapping("role", "id", Role.class);
		arp.addMapping("seo", "id", Seo.class);
		arp.addMapping("shipping_method", "id", ShippingMethod.class);
		// Composite Primary Key order: payment_methods_id,shipping_methods_id
		arp.addMapping("shipping_method_payment_method", "payment_methods_id,shipping_methods_id", ShippingMethodPaymentMethod.class);
		arp.addMapping("sku", "id", Sku.class);
		arp.addMapping("sku_barcode", "id", SkuBarcode.class);
		arp.addMapping("sms", "id", Sms.class);
		arp.addMapping("sn", "id", Sn.class);
		arp.addMapping("social_user", "id", SocialUser.class);
		arp.addMapping("specification", "id", Specification.class);
		arp.addMapping("statistic", "id", Statistic.class);
		arp.addMapping("stock_log", "id", StockLog.class);
		arp.addMapping("store", "id", Store.class);
		arp.addMapping("store_ad_image", "id", StoreAdImage.class);
		arp.addMapping("store_category", "id", StoreCategory.class);
		arp.addMapping("store_favorite", "id", StoreFavorite.class);
		arp.addMapping("store_product_category", "id", StoreProductCategory.class);
		arp.addMapping("store_product_tag", "id", StoreProductTag.class);
		arp.addMapping("store_rank", "id", StoreRank.class);
		arp.addMapping("svc", "id", Svc.class);
		arp.addMapping("user", "id", User.class);
	}
}

