package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseMemberRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemberRole extends BaseMemberRole<MemberRole> {
	public static final MemberRole dao = new MemberRole().dao();
}
