package com.jfinalshop.model;

import com.jfinalshop.model.base.BasePlatformSvc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlatformSvc extends BasePlatformSvc<PlatformSvc> {
	public static final PlatformSvc dao = new PlatformSvc().dao();
}
