package com.jfinalshop.model;

import com.jfinalshop.model.base.BasePromotionPluginSvc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PromotionPluginSvc extends BasePromotionPluginSvc<PromotionPluginSvc> {
	public static final PromotionPluginSvc dao = new PromotionPluginSvc().dao();
}
